ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # The frequency at which to run the filter (Hz)
    sensor_timeout: 0.1  # Timeout for sensor data in seconds
    two_d_mode: false  # If true, the filter will ignore Z-axis data
    publish_tf: true  # Publish the transform between the base_link and the world frame
    print_diagnostics: true  # Print diagnostics to the console
    
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    #map_frame: map
    
    
    # Specify the odometry input
    odom0: /odom_noisy
    odom0_config: [false, false, false,  # x, y, z
                    false, false, false,  # roll, pitch, yaw
                   true, true, false,     # Vx, Vy, Vz
                   false, false, true,   # Vroll, Vpitch, Vyaw
                   false, false, false]  # Ax, Ay, Az
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # Specify the IMU input
    imu0: /imu
    imu0_config: [false, false, false,  # x, y, z
                 false, false, false,    # roll, pitch, yaw
                  false, false, false,  # Vx, Vy, Vz
                  false, false, true,    # Vroll, Vpitch, Vyaw
                  true, false, false]    # Ax, Ay, Az
    imu0_differential: false
    imu0_queue_size: 10

    # Initial covariance for the filter state
   # initial_estimate_covariance: [1.0e-5, 0.0, 0.0, 0.0, 0.0, 0.0,
   #                               0.0, 1.0e-5, 0.0, 0.0, 0.0, 0.0,
   #                               0.0, 0.0, 1000000000000.0, 0.0, 0.0, 0.0,
   #                               0.0, 0.0, 0.0, 1000000000000.0, 0.0, 0.0,
  #                                0.0, 0.0, 0.0, 0.0, 1000000000000.0, 0.0,
  #                                0.0, 0.0, 0.0, 0.0, 0.0, 0.001]

    # Process noise covariance
   # process_noise_covariance: [0.001, 0.0, 0.0, 0.0, 0.0, 0.0,
   #                            0.0, 0.001, 0.0, 0.0, 0.0, 0.0,
    #                          0.0, 0.0, 0.001, 0.0, 0.0, 0.0,
    #                          0.0, 0.0, 0.0, 0.001, 0.0, 0.0,
     #                         0.0, 0.0, 0.0, 0.0, 0.001, 0.0,
    #                          0.0, 0.0, 0.0, 0.0, 0.0, 0.001]

    # Control input for the filter
    use_control: false

